variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Définit l'emplacement du cache de tâche d'analyse
  GIT_DEPTH: "0"  # Indique à Git de récupérer toutes les branches du projet, requis par la tâche d'analyse

sonarcloud-check:
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
    - sonar-scanner -Dsonar.qualitygate.wait=true -Dsonar.security.enable=true -X
  only:
    - merge_requests
    - main
    - master
    - develop
