
lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem' # required for token creation
    public_key: '%kernel.project_dir%/config/jwt/public.pem' # required for token verification
    pass_phrase: 'resources relationnelles projet du cesi cube' # required for token creation
    token_ttl: 3600 # in seconds, default is 3600
    api_platform:
        check_path: /api/login_check
        username_path: email
        password_path: security.credentials.password
    token_extractors:
        query_parameter:
            enabled: true
            name: Bearer